// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CaregiverCombineReturn struct {
	CnStatus       int      `json:"cnStatus"`
	CsBytePhoto    string   `json:"csBytePhoto"`
	CnImgAvatarID  int      `json:"cnImgAvatarId"`
	CsFirstName    string   `json:"csFirstName"`
	CsLastName     string   `json:"csLastName"`
	CsNickName     string   `json:"csNickName"`
	CnRelation     int      `json:"cnRelation"`
	CnFamilySize   int      `json:"cnFamilySize"`
	CnMarriage     int      `json:"cnMarriage"`
	CsDateBirth    string   `json:"csDateBirth"`
	CsNationID     string   `json:"csNationId"`
	CIsSameAddress bool     `json:"cIsSameAddress"`
	CsAddress      string   `json:"csAddress"`
	CsKwang        string   `json:"csKwang"`
	CsKhet         string   `json:"csKhet"`
	CsProvince     string   `json:"csProvince"`
	CsPost         string   `json:"csPost"`
	CsCountry      string   `json:"csCountry"`
	CsEmail        string   `json:"csEmail"`
	CsLineID       string   `json:"csLineId"`
	CsTel          string   `json:"csTel"`
	CrsStaffUID    []string `json:"crsStaffUID"`
	CrsClinicUID   []string `json:"crsClinicUID"`
	CrsPatientUID  []string `json:"crsPatientUID"`
}

type CaregiverProfileEdit struct {
	SSessionUIDc  string   `json:"sSessionUIDC"`
	NStatus       int      `json:"nStatus"`
	SBytePhoto    string   `json:"sBytePhoto"`
	NImgAvatarID  int      `json:"nImgAvatarId"`
	SFirstName    string   `json:"sFirstName"`
	SLastName     string   `json:"sLastName"`
	SNickName     string   `json:"sNickName"`
	NRelation     int      `json:"nRelation"`
	NFamilySize   int      `json:"nFamilySize"`
	SDateBirth    string   `json:"sDateBirth"`
	SNationID     string   `json:"sNationId"`
	IsSameAddress bool     `json:"IsSameAddress"`
	SAddress      string   `json:"sAddress"`
	SKwang        string   `json:"sKwang"`
	SKhet         string   `json:"sKhet"`
	SProvince     string   `json:"sProvince"`
	SPost         string   `json:"sPost"`
	SCountry      string   `json:"sCountry"`
	SEmail        string   `json:"sEmail"`
	SLineID       string   `json:"sLineId"`
	STel          string   `json:"sTel"`
	RsPatientUID  []string `json:"rsPatientUID"`
}

type CaregiverProfileRegister struct {
	NStatus       int      `json:"nStatus"`
	SBytePhoto    string   `json:"sBytePhoto"`
	NImgAvatarID  int      `json:"nImgAvatarId"`
	SFirstName    string   `json:"sFirstName"`
	SLastName     string   `json:"sLastName"`
	SNickName     string   `json:"sNickName"`
	NRelation     int      `json:"nRelation"`
	NFamilySize   int      `json:"nFamilySize"`
	SDateBirth    string   `json:"sDateBirth"`
	SNationID     string   `json:"sNationId"`
	IsSameAddress bool     `json:"IsSameAddress"`
	SAddress      string   `json:"sAddress"`
	SKwang        string   `json:"sKwang"`
	SKhet         string   `json:"sKhet"`
	SProvince     string   `json:"sProvince"`
	SPost         string   `json:"sPost"`
	SCountry      string   `json:"sCountry"`
	SEmail        string   `json:"sEmail"`
	SLineID       string   `json:"sLineId"`
	STel          string   `json:"sTel"`
	RsPatientUID  []string `json:"rsPatientUID"`
}

type ChangeEmailIn struct {
	SSessionUIDs string `json:"sSessionUIDS"`
	SNewEmail    string `json:"sNewEmail"`
	SPassword    string `json:"sPassword"`
}

type ChangePwdin struct {
	SSessionUIDs string `json:"sSessionUIDS"`
	SNewPassword string `json:"sNewPassword"`
	SPassword    string `json:"sPassword"`
}

type ChangePhoneIn struct {
	SSessionUIDs string `json:"sSessionUIDS"`
	SNewPhone    string `json:"sNewPhone"`
	SPassword    string `json:"sPassword"`
}

type ClinicAppData struct {
	NStatus        int      `json:"nStatus"`
	SBytePhoto     string   `json:"sBytePhoto"`
	SName          string   `json:"sName"`
	SAddress       string   `json:"sAddress"`
	SKwang         string   `json:"sKwang"`
	SKhet          string   `json:"sKhet"`
	SProvince      string   `json:"sProvince"`
	SPost          string   `json:"sPost"`
	SCountry       string   `json:"sCountry"`
	SEmail         string   `json:"sEmail"`
	STel           string   `json:"sTel"`
	SLineID        string   `json:"sLineId"`
	SLat           string   `json:"sLat"`
	SLong          string   `json:"sLong"`
	RsStaff        []string `json:"rsStaff"`
	RsClinicUID    []string `json:"rsClinicUID"`
	RsCaregiverUID []string `json:"rsCaregiverUID"`
}

type ClinicAppReturn struct {
	SStatus        string              `json:"sStatus"`
	SSessionUIDc   string              `json:"sSessionUIDC"`
	SSessionUIDs   string              `json:"sSessionUIDS"`
	MClinicAppData *ClinicAppData      `json:"mClinicAppData"`
	MStaffProfile  *StaffProfileReturn `json:"mStaffProfile"`
}

type ClinicProfileCreate struct {
	SSessionUIDc string `json:"sSessionUIDC"`
	NStatus      int    `json:"nStatus"`
	SBytePhoto   string `json:"sBytePhoto"`
	SName        string `json:"sName"`
	SAddress     string `json:"sAddress"`
	SKwang       string `json:"sKwang"`
	SKhet        string `json:"sKhet"`
	SProvince    string `json:"sProvince"`
	SPost        string `json:"sPost"`
	SCountry     string `json:"sCountry"`
	SEmail       string `json:"sEmail"`
	STel         string `json:"sTel"`
	SLineID      string `json:"sLineId"`
	SLat         string `json:"sLat"`
	SLong        string `json:"sLong"`
}

type GetListData struct {
	SSessionUIDc string `json:"sSessionUIDC"`
	SSessionUIDs string `json:"sSessionUIDS"`
}

type GetPatientListReturn struct {
	SStatus      string         `json:"sStatus"`
	RPatientList []*PatientList `json:"rPatientList"`
}

type GetStaffData struct {
	SSessionUIDs string `json:"sSessionUIDS"`
}

type GetStaffListReturn struct {
	SStatus    string       `json:"sStatus"`
	RStaffList []*StaffList `json:"rStaffList"`
}

type Login struct {
	SEmail          string `json:"sEmail"`
	SPass           string `json:"sPass"`
	Attempt         int    `json:"attempt"`
	Signintime      string `json:"signintime"`
	NtimestampFront int    `json:"ntimestampFront"`
}

type MsDoctor struct {
	NSymptom     int    `json:"nSymptom"`
	SSessionUIDs string `json:"sSessionUIDS"`
}

type PatientAndCaregiverCreate struct {
	SSessionUIDc     string      `json:"sSessionUIDC"`
	SSessionUIDs     string      `json:"sSessionUIDS"`
	PntimestampFront int         `json:"pntimestampFront"`
	PnStatus         int         `json:"pnStatus"`
	PsBytePhoto      string      `json:"psBytePhoto"`
	PnImgAvatarID    int         `json:"pnImgAvatarId"`
	PsEmail          string      `json:"psEmail"`
	PsFirstName      string      `json:"psFirstName"`
	PsLastName       string      `json:"psLastName"`
	PsNickName       string      `json:"psNickName"`
	PnGender         int         `json:"pnGender"`
	PsDateBirth      string      `json:"psDateBirth"`
	PsNationID       string      `json:"psNationId"`
	PsAddress        string      `json:"psAddress"`
	PsKwang          string      `json:"psKwang"`
	PsKhet           string      `json:"psKhet"`
	PsProvince       string      `json:"psProvince"`
	PsPost           string      `json:"psPost"`
	PsCountry        string      `json:"psCountry"`
	PsTel            string      `json:"psTel"`
	PsLineID         string      `json:"psLineId"`
	PnWhoPay         int         `json:"pnWhoPay"`
	PisGotCaregiver  *bool       `json:"pisGotCaregiver"`
	PrsDoctorUID     []*MsDoctor `json:"prsDoctorUID"`
	CnStatus         int         `json:"cnStatus"`
	CsBytePhoto      string      `json:"csBytePhoto"`
	CnImgAvatarID    int         `json:"cnImgAvatarId"`
	CsFirstName      string      `json:"csFirstName"`
	CsLastName       string      `json:"csLastName"`
	CsNickName       string      `json:"csNickName"`
	CnRelation       int         `json:"cnRelation"`
	CnFamilySize     int         `json:"cnFamilySize"`
	CnMarriage       *int        `json:"cnMarriage"`
	CsDateBirth      string      `json:"csDateBirth"`
	CsNationID       string      `json:"csNationId"`
	CIsSameAddress   bool        `json:"cIsSameAddress"`
	CsAddress        string      `json:"csAddress"`
	CsKwang          string      `json:"csKwang"`
	CsKhet           string      `json:"csKhet"`
	CsProvince       string      `json:"csProvince"`
	CsPost           string      `json:"csPost"`
	CsCountry        string      `json:"csCountry"`
	CsEmail          string      `json:"csEmail"`
	CsLineID         string      `json:"csLineId"`
	CsTel            string      `json:"csTel"`
}

type PatientAndCaregiverEdit struct {
	SSessionUIDp     string      `json:"sSessionUIDP"`
	SSessionUIDc     string      `json:"sSessionUIDC"`
	SSessionUIDs     string      `json:"sSessionUIDS"`
	SSessionUIDCa    string      `json:"sSessionUIDCa"`
	PntimestampFront int         `json:"pntimestampFront"`
	PnStatus         int         `json:"pnStatus"`
	PsBytePhoto      string      `json:"psBytePhoto"`
	PnImgAvatarID    int         `json:"pnImgAvatarId"`
	PsEmail          string      `json:"psEmail"`
	PsFirstName      string      `json:"psFirstName"`
	PsLastName       string      `json:"psLastName"`
	PsNickName       string      `json:"psNickName"`
	PnGender         int         `json:"pnGender"`
	PsDateBirth      string      `json:"psDateBirth"`
	PsNationID       string      `json:"psNationId"`
	PsAddress        string      `json:"psAddress"`
	PsKwang          string      `json:"psKwang"`
	PsKhet           string      `json:"psKhet"`
	PsProvince       string      `json:"psProvince"`
	PsPost           string      `json:"psPost"`
	PsCountry        string      `json:"psCountry"`
	PsTel            string      `json:"psTel"`
	PsLineID         string      `json:"psLineId"`
	PnWhoPay         int         `json:"pnWhoPay"`
	PisGotCaregiver  *bool       `json:"pisGotCaregiver"`
	PrsCaregiverUID  []string    `json:"prsCaregiverUID"`
	PrsStaffUID      []string    `json:"prsStaffUID"`
	PrsClinicUID     []string    `json:"prsClinicUID"`
	PrsDoctorUID     []*MsDoctor `json:"prsDoctorUID"`
	CnStatus         int         `json:"cnStatus"`
	CsBytePhoto      string      `json:"csBytePhoto"`
	CnImgAvatarID    int         `json:"cnImgAvatarId"`
	CsFirstName      string      `json:"csFirstName"`
	CsLastName       string      `json:"csLastName"`
	CsNickName       string      `json:"csNickName"`
	CnRelation       int         `json:"cnRelation"`
	CnFamilySize     int         `json:"cnFamilySize"`
	CsDateBirth      string      `json:"csDateBirth"`
	CsNationID       string      `json:"csNationId"`
	CnMarriage       *int        `json:"cnMarriage"`
	CIsSameAddress   bool        `json:"cIsSameAddress"`
	CsAddress        string      `json:"csAddress"`
	CsKwang          string      `json:"csKwang"`
	CsKhet           string      `json:"csKhet"`
	CsProvince       string      `json:"csProvince"`
	CsPost           string      `json:"csPost"`
	CsCountry        string      `json:"csCountry"`
	CsEmail          string      `json:"csEmail"`
	CsLineID         string      `json:"csLineId"`
	CsTel            string      `json:"csTel"`
	CrsStaffUID      []string    `json:"crsStaffUID"`
	CrsClinicUID     []string    `json:"crsClinicUID"`
	CrsPatientUID    []string    `json:"crsPatientUID"`
}

type PatientAndCaregiverReturn struct {
	SStatus                 string                  `json:"sStatus"`
	MPatientCombineReturn   *PatientCombineReturn   `json:"mPatientCombineReturn"`
	MCaregiverCombineReturn *CaregiverCombineReturn `json:"mCaregiverCombineReturn"`
}

type PatientCombineReturn struct {
	PntimestampFront int               `json:"pntimestampFront"`
	PnStatus         int               `json:"pnStatus"`
	PsBytePhoto      string            `json:"psBytePhoto"`
	PnImgAvatarID    int               `json:"pnImgAvatarId"`
	PsEmail          string            `json:"psEmail"`
	PsFirstName      string            `json:"psFirstName"`
	PsLastName       string            `json:"psLastName"`
	PsNickName       string            `json:"psNickName"`
	PnGender         int               `json:"pnGender"`
	PsDateBirth      string            `json:"psDateBirth"`
	PsNationID       string            `json:"psNationId"`
	PsAddress        string            `json:"psAddress"`
	PsKwang          string            `json:"psKwang"`
	PsKhet           string            `json:"psKhet"`
	PsProvince       string            `json:"psProvince"`
	PsPost           string            `json:"psPost"`
	PsCountry        string            `json:"psCountry"`
	PsTel            string            `json:"psTel"`
	PsLineID         string            `json:"psLineId"`
	PnWhoPay         int               `json:"pnWhoPay"`
	PisGotCaregiver  bool              `json:"pisGotCaregiver"`
	PrsCaregiverUID  []string          `json:"prsCaregiverUID"`
	PrsStaffUID      []string          `json:"prsStaffUID"`
	PrsClinicUID     []string          `json:"prsClinicUID"`
	PrsDoctorUID     []*MsDoctorReturn `json:"prsDoctorUID"`
}

type PatientList struct {
	SUID         string            `json:"sUID"`
	SBytePhoto   string            `json:"sBytePhoto"`
	NImgAvatarID int               `json:"nImgAvatarId"`
	SFirstName   string            `json:"sFirstName"`
	SLastName    string            `json:"sLastName"`
	SNickName    string            `json:"sNickName"`
	NGender      int               `json:"nGender"`
	RTeleSession []string          `json:"rTeleSession"`
	RsDoctorUID  []*MsDoctorReturn `json:"rsDoctorUID"`
}

type MsDoctorReturn struct {
	NSymptom     int    `json:"nSymptom"`
	SSessionUIDs string `json:"sSessionUIDS"`
}

type PatientProfileCreate struct {
	SSessionUIDc    string   `json:"sSessionUIDC"`
	NtimestampFront int      `json:"ntimestampFront"`
	NStatus         int      `json:"nStatus"`
	SBytePhoto      string   `json:"sBytePhoto"`
	NImgAvatarID    int      `json:"nImgAvatarId"`
	SEmail          string   `json:"sEmail"`
	SFirstName      string   `json:"sFirstName"`
	SLastName       string   `json:"sLastName"`
	SNickName       string   `json:"sNickName"`
	NGender         int      `json:"nGender"`
	SDateBirth      string   `json:"sDateBirth"`
	SNationID       string   `json:"sNationId"`
	SAddress        string   `json:"sAddress"`
	SKwang          string   `json:"sKwang"`
	SKhet           string   `json:"sKhet"`
	SProvince       string   `json:"sProvince"`
	SPost           string   `json:"sPost"`
	SCountry        string   `json:"sCountry"`
	STel            string   `json:"sTel"`
	SLineID         string   `json:"sLineId"`
	NWhoPay         int      `json:"nWhoPay"`
	RnSymptom       []int    `json:"rnSymptom"`
	RsCaregiverUID  []string `json:"rsCaregiverUID"`
	RsStaffUID      []string `json:"rsStaffUID"`
	RsClinicUID     []string `json:"rsClinicUID"`
	RsDoctorUID     []string `json:"rsDoctorUID"`
}

type PatientProfileEdit struct {
	SSessionUIDp             string   `json:"sSessionUIDP"`
	NtimestampFront          int      `json:"ntimestampFront"`
	NStatus                  int      `json:"nStatus"`
	SBytePhoto               string   `json:"sBytePhoto"`
	NImgAvatarID             int      `json:"nImgAvatarId"`
	SEmail                   string   `json:"sEmail"`
	SFirstName               string   `json:"sFirstName"`
	SLastName                string   `json:"sLastName"`
	SNickName                string   `json:"sNickName"`
	NGender                  int      `json:"nGender"`
	SDateBirth               string   `json:"sDateBirth"`
	SNationID                string   `json:"sNationId"`
	SAddress                 string   `json:"sAddress"`
	SKwang                   string   `json:"sKwang"`
	SKhet                    string   `json:"sKhet"`
	SProvince                string   `json:"sProvince"`
	SPost                    string   `json:"sPost"`
	SCountry                 string   `json:"sCountry"`
	STel                     string   `json:"sTel"`
	SLineID                  string   `json:"sLineId"`
	NWhoPay                  int      `json:"nWhoPay"`
	IsUpdateonlyProfileModel bool     `json:"isUpdateonlyProfileModel"`
	RnSymptom                []int    `json:"rnSymptom"`
	RsCaregiverUID           []string `json:"rsCaregiverUID"`
	RsStaffUID               []string `json:"rsStaffUID"`
	RsClinicUID              []string `json:"rsClinicUID"`
	RsDoctorUID              []string `json:"rsDoctorUID"`
}

type RegisterPatientReturn struct {
	SStatus      string `json:"sStatus"`
	SSessionUIDs string `json:"sSessionUIDS"`
}

type RequestNormalC struct {
	SSessionUIDc    string `json:"sSessionUIDC"`
	SSessionUIDs    string `json:"sSessionUIDS"`
	NtimestampFront int    `json:"ntimestampFront"`
}

type ReturnLogin struct {
	SStatus          string   `json:"sStatus"`
	SSessionUIDc     []string `json:"sSessionUIDC"`
	SSessionUIDs     string   `json:"sSessionUIDS"`
	SClinicUID       string   `json:"sClinicUID"`
	NRoleid          int      `json:"nRoleid"`
	NAccountstatus   int      `json:"nAccountstatus"`
	NSessionlifetime int      `json:"nSessionlifetime"`
}

type StaffList struct {
	SUID           string `json:"sUID"`
	SBytePhoto     string `json:"sBytePhoto"`
	NImgAvatarID   int    `json:"nImgAvatarId"`
	NTitle         int    `json:"nTitle"`
	SFirstName     string `json:"sFirstName"`
	SLastName      string `json:"sLastName"`
	SNickName      string `json:"sNickName"`
	NGender        int    `json:"nGender"`
	SMDCardNumbers string `json:"sMDCardNumbers"`
	RnSymptom      []int  `json:"rnSymptom"`
}

type StaffProfile struct {
	SStatus        string `json:"sStatus"`
	SSessionUIDc   string `json:"sSessionUIDC"`
	NStatus        int    `json:"nStatus"`
	SBytePhoto     string `json:"sBytePhoto"`
	SEmail         string `json:"sEmail"`
	SPass          string `json:"sPass"`
	SFirstName     string `json:"sFirstName"`
	SLastName      string `json:"sLastName"`
	SNickName      string `json:"sNickName"`
	NGender        int    `json:"nGender"`
	SDateBirth     string `json:"sDateBirth"`
	SDrOfficialID  string `json:"sDrOfficialId"`
	SAddress       string `json:"sAddress"`
	SKwang         string `json:"sKwang"`
	SKhet          string `json:"sKhet"`
	SProvince      string `json:"sProvince"`
	SPost          string `json:"sPost"`
	SCountry       string `json:"sCountry"`
	STel           string `json:"sTel"`
	SLineID        string `json:"sLineId"`
	NImgAvatarID   int    `json:"nImgAvatarId"`
	NTitle         int    `json:"nTitle"`
	SMDCardNumbers string `json:"sMDCardNumbers"`
	RnSymptom      []int  `json:"rnSymptom"`
}

type StaffProfileEdit struct {
	SSessionUIDs   string   `json:"sSessionUIDS"`
	NStatus        *int     `json:"nStatus"`
	SBytePhoto     *string  `json:"sBytePhoto"`
	SEmail         *string  `json:"sEmail"`
	SFirstName     *string  `json:"sFirstName"`
	SLastName      *string  `json:"sLastName"`
	SNickName      *string  `json:"sNickName"`
	NGender        *int     `json:"nGender"`
	SDateBirth     *string  `json:"sDateBirth"`
	SDrOfficialID  *string  `json:"sDrOfficialId"`
	SAddress       *string  `json:"sAddress"`
	SKwang         *string  `json:"sKwang"`
	SKhet          *string  `json:"sKhet"`
	SProvince      *string  `json:"sProvince"`
	SPost          *string  `json:"sPost"`
	SCountry       *string  `json:"sCountry"`
	STel           *string  `json:"sTel"`
	SLineID        *string  `json:"sLineId"`
	NImgAvatarID   *int     `json:"nImgAvatarId"`
	NTitle         *int     `json:"nTitle"`
	SMDCardNumbers *string  `json:"sMDCardNumbers"`
	RnSymptom      []int    `json:"rnSymptom"`
	RsCaregiverUID []string `json:"rsCaregiverUID"`
	RsClinicUID    []string `json:"rsClinicUID"`
}

type StaffProfileRegister struct {
	SSessionUIDc   string `json:"sSessionUIDC"`
	NStatus        int    `json:"nStatus"`
	SBytePhoto     string `json:"sBytePhoto"`
	SEmail         string `json:"sEmail"`
	SPass          string `json:"sPass"`
	SFirstName     string `json:"sFirstName"`
	SLastName      string `json:"sLastName"`
	SNickName      string `json:"sNickName"`
	NGender        int    `json:"nGender"`
	SDateBirth     string `json:"sDateBirth"`
	SDrOfficialID  string `json:"sDrOfficialId"`
	SAddress       string `json:"sAddress"`
	SKwang         string `json:"sKwang"`
	SKhet          string `json:"sKhet"`
	SProvince      string `json:"sProvince"`
	SPost          string `json:"sPost"`
	SCountry       string `json:"sCountry"`
	STel           string `json:"sTel"`
	SLineID        string `json:"sLineId"`
	NImgAvatarID   int    `json:"nImgAvatarId"`
	NTitle         int    `json:"nTitle"`
	SMDCardNumbers string `json:"sMDCardNumbers"`
	RnSymptom      []int  `json:"rnSymptom"`
}

type StaffProfileReturn struct {
	NStatus        int      `json:"nStatus"`
	SBytePhoto     string   `json:"sBytePhoto"`
	SEmail         string   `json:"sEmail"`
	SFirstName     string   `json:"sFirstName"`
	SLastName      string   `json:"sLastName"`
	SNickName      string   `json:"sNickName"`
	NGender        int      `json:"nGender"`
	SDateBirth     string   `json:"sDateBirth"`
	SDrOfficialID  string   `json:"sDrOfficialId"`
	SAddress       string   `json:"sAddress"`
	SKwang         string   `json:"sKwang"`
	SKhet          string   `json:"sKhet"`
	SProvince      string   `json:"sProvince"`
	SPost          string   `json:"sPost"`
	SCountry       string   `json:"sCountry"`
	STel           string   `json:"sTel"`
	SLineID        string   `json:"sLineId"`
	RsCaregiverUID []string `json:"rsCaregiverUID"`
}

type GetPatientAndCaregiverData struct {
	SSessionUIDp string `json:"sSessionUIDP"`
	SSessionUIDc string `json:"sSessionUIDC"`
	SSessionUIDs string `json:"sSessionUIDS"`
}
